In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv(r'C:\Users\kazir\OneDrive\Desktop\Github\NBA\CSVs\nbaV2.csv', drop)

In [7]:
df.head()

,Unnamed: 0,player,season,seasonPhase,startTime,homeTeamId,homeScore,awayTeamId,awayScore,displayResult,...,OFFENSIVE_REBOUNDS,DEFENSIVE_REBOUNDS,TOTAL_REBOUNDS,ASSISTS,TURNOVERS,STEALS,BLOCKS,FOULS,PLUS_MINUS,POINTS
0,0,Nikola Jokic,2015,REGULAR_SEASON,2016-04-13T22:30:00-04:00,nba.t.22,107,nba.t.7,99,L 99-107,...,6,7,13,5,2,0,0,3,4,18
1,1,Nikola Jokic,2015,REGULAR_SEASON,2016-04-10T17:00:00-04:00,nba.t.7,84,nba.t.26,100,L 100-84,...,3,8,11,4,1,2,1,4,-16,19
2,2,Nikola Jokic,2015,REGULAR_SEASON,2016-04-08T21:00:00-04:00,nba.t.7,102,nba.t.24,98,W 98-102,...,3,12,15,4,0,1,1,2,24,8
3,3,Nikola Jokic,2015,REGULAR_SEASON,2016-04-05T21:00:00-04:00,nba.t.7,102,nba.t.25,124,L 124-102,...,0,2,2,2,0,0,2,2,-9,7
4,4,Nikola Jokic,2015,REGULAR_SEASON,2016-04-02T21:00:00-04:00,nba.t.7,106,nba.t.23,115,L 115-106,...,4,9,13,5,0,1,2,2,-1,6

In [5]:
df.POINTS.mean()

11.782905163188088